CI Updates (#7)

diff --git a/.github/workflows/xcodetest.yml b/.github/workflows/xcodetest.yml
--- a/.github/workflows/xcodetest.yml
+++ b/.github/workflows/xcodetest.yml
@@ -4,13 +4,13 @@ on: [push, pull_request]
 
 jobs:
   Test:
-    runs-on: macos-11
+    runs-on: macos-15
 
     steps:
     - uses: actions/checkout@v2
 
     - name: Select Xcode
-      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
+      run: sudo xcode-select -switch /Applications/Xcode_16.1.app
 
     - name: Xcode version
       run: /usr/bin/xcodebuild -version
@@ -18,9 +18,9 @@ jobs:
     - name: Xcode unit tests
       run: |
         cd Xcode/
-        xcodebuild clean test -scheme TheNews -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' -resultBundlePath TestResults
+        xcodebuild clean test -scheme TheNews -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' -resultBundlePath TestResults
 
-    - uses: kishikawakatsumi/xcresulttool@v1
-      with:
-        path: Xcode/TestResults.xcresult
-      if: success() || failure()
+    # - uses: kishikawakatsumi/xcresulttool@v1
+    #   with:
+    #     path: Xcode/TestResults.xcresult
+    #   if: success() || failure()
